# frozen_string_literal: true

# Generated by Selenium IDE
require 'selenium-webdriver'
require 'json'
describe 'Withoutlogin' do
  before(:each) do
    @driver = Selenium::WebDriver.for :firefox
    @vars = {}
  end
  after(:each) do
    @driver.quit
  end
  it 'withoutlogin' do
    @driver.get('http://localhost:3000/')
    @driver.find_element(:id, 'number1').click
    @driver.find_element(:id, 'number1').send_keys('1')
    @driver.find_element(:id, 'number2').click
    @driver.find_element(:id, 'number2').send_keys('1')
    @driver.find_element(:name, 'commit').click
    Selenium::WebDriver::Wait.new(timeout: 2).until { @driver.find_element(:css, 'h1').displayed? }
    expect(@driver.find_element(:css, 'h1').text).to eq('Sign in')
  end
end
