# Generated by Selenium IDE
require 'selenium-webdriver'
require 'json'

# Добавление админом упражнения и последующее его удаление
describe '10addAnddeleteExercise' do
  before(:each) do
    @driver = Selenium::WebDriver.for :chrome
    @vars = {}
  end
  after(:each) do
    @driver.quit
  end
  it '10addAnddeleteExercise' do
    @driver.get('http://localhost:3000/')
    @driver.manage.window.resize_to(1920, 1040)
    @driver.find_element(:link_text, 'Войти в аккаунт').click
    sleep 2
    @driver.find_element(:id, 'email').click
    @driver.find_element(:id, 'email').send_keys('dt.71dt@mail.ru')
    @driver.find_element(:id, 'password').click
    @driver.find_element(:id, 'password').send_keys('Dimon2023')
    @driver.find_element(:name, 'commit').click
    sleep 2
    @driver.find_element(:link_text, 'Добавить новое упражнение в каталог').click
    sleep 2
    @driver.find_element(:id, 'exercise_image').send_keys('/home/d3metra/Рабочий стол/Ruby/soreva_3.0/soreva_app/spec/support/assets/test_img.jpg')
    @driver.find_element(:id, 'exercise_name').click
    @driver.find_element(:id, 'exercise_name').send_keys('123')
    @driver.find_element(:id, 'exercise_description').click
    @driver.find_element(:id, 'exercise_description').send_keys('123')
    @driver.find_element(:id, 'exercise_technique').click
    @driver.find_element(:id, 'exercise_technique').send_keys('123')
    @driver.find_element(:name, 'commit').click
    sleep 2
    @driver.find_element(:css, '.row:nth-child(2) > .btn').click
    sleep 2
    @driver.find_element(:link_text, '123').click
    sleep 2
    @driver.find_element(:css, '#dropdownMenuButton > img').click
    sleep 2
    @driver.find_element(:css, '.btn-danger').click
    sleep 3
    expect(@driver.find_element(:css, '.notice-message').text).to eq('Упражнение удалено из каталога')
  end
end
