# Generated by Selenium IDE
require 'selenium-webdriver'
require 'json'

# Тестируем возможность неавторизованного пользователя посмотреть упражнение
describe 'ShowExerciseWithoutLogin' do
  before(:each) do
    @driver = Selenium::WebDriver.for :chrome
    @vars = {}
  end
  after(:each) do
    @driver.quit
  end
  it 'showExerciseWithoutLogin' do
    @driver.get('http://localhost:3000/')
    @driver.manage.window.resize_to(1920, 1040)
    @driver.find_element(:css, '.row:nth-child(2) > .btn').click
    sleep 1
    @driver.find_element(:link_text, 'Жим штанги лежа').click
    sleep 1
    expect(@driver.find_element(:css, '.font-monospace').text).to eq('Жим штанги лежа')
    @driver.find_element(:css, '.btn-outline-dark').click
    sleep 1
    elements = @driver.find_elements(:css, '#description > .fs-5:nth-child(1)')
    expect(elements.length).to be > 0
  end
end
