# Generated by Selenium IDE
require 'selenium-webdriver'
require 'json'

# Тестируем возможность неавторизованного пользователя зайти в профиль пользователя сайта 
describe 'ShowUsersProfileWithoutLogin' do
  before(:each) do
    @driver = Selenium::WebDriver.for :chrome
    @vars = {}
  end
  after(:each) do
    @driver.quit
  end
  it 'showUsersProfileWithoutLogin' do
    @driver.get('http://localhost:3000/')
    @driver.manage.window.resize_to(1920, 1040)
    @driver.find_element(:link_text, 'Пользователи').click
    sleep 1
    @driver.find_element(:link_text, 'ChuckNorris').click
    sleep 1
    expect(@driver.find_element(:css, '.ms-5').text).to eq('ChuckNorris')
  end
end
