# Generated by Selenium IDE
require 'selenium-webdriver'
require 'json'

# Тестируем попытку неавторизованного пользователя посетить страницу соревнований
describe '3competentionWithoutLogin' do
  before(:each) do
    @driver = Selenium::WebDriver.for :chrome
    @vars = {}
  end
  after(:each) do
    @driver.quit
  end
  it '3competentionWithoutLogin' do
    @driver.get('http://localhost:3000/')
    @driver.manage.window.resize_to(1920, 1040)
    @driver.find_element(:link_text, 'Соревнования').click
    sleep 1
    expect(@driver.find_element(:css, 'h2').text).to eq('Войти в аккаунт')
  end
end
