# Generated by Selenium IDE
require 'selenium-webdriver'
require 'json'

# Регистрация нового пользователя testuser
describe '4registration' do
  before(:each) do
    @driver = Selenium::WebDriver.for :chrome
    @vars = {}
  end
  after(:each) do
    @driver.quit
  end
  it '4registration' do
    @driver.get('http://localhost:3000/')
    @driver.manage.window.resize_to(1920, 1040)
    @driver.find_element(:link_text, 'Зарегистрироваться').click
    sleep 2
    @driver.find_element(:id, 'user_username').click
    @driver.find_element(:id, 'user_username').send_keys('testuser')
    @driver.find_element(:id, 'user_email').click
    @driver.find_element(:id, 'user_email').send_keys('testuser@email.ru')
    @driver.find_element(:id, 'user_password').click
    @driver.find_element(:id, 'user_password').send_keys('123456')
    @driver.find_element(:id, 'user_password_confirmation').click
    @driver.find_element(:id, 'user_password_confirmation').send_keys('123456')
    @driver.find_element(:name, 'commit').click
    sleep 3
    expect(@driver.find_element(:css, '.notice-message').text).to eq('Вы успешно зарегистрированы')
  end
end
