# Generated by Selenium IDE
require 'selenium-webdriver'
require 'json'

# Авторизация пользователя testuser, проверка обновления списка пользователей и поиска пользователя
describe '5login' do
  before(:each) do
    @driver = Selenium::WebDriver.for :chrome
    @vars = {}
  end
  after(:each) do
    @driver.quit
  end
  it '5login' do
    @driver.get('http://localhost:3000/')
    @driver.manage.window.resize_to(1920, 1040)
    @driver.find_element(:link_text, 'Войти в аккаунт').click
    sleep 2
    @driver.find_element(:id, 'email').click
    @driver.find_element(:id, 'email').send_keys('testuser@email.ru')
    @driver.find_element(:id, 'password').click
    @driver.find_element(:id, 'password').send_keys('123456')
    @driver.find_element(:name, 'commit').click
    sleep 2
    expect(@driver.find_element(:css, '.notice-message').text).to eq('Вы успешно вошли в аккаунт!')
    @driver.find_element(:link_text, 'Пользователи').click
    sleep 2
    expect(@driver.find_element(:link_text, 'testuser').text).to eq('testuser')
    @driver.find_element(:id, 'username_search').click
    @driver.find_element(:id, 'username_search').send_keys('test')
    @driver.find_element(:name, 'commit').click
    sleep 2
    expect(@driver.find_element(:link_text, 'testuser').text).to eq('testuser')
  end
end
