# Generated by Selenium IDE
require 'selenium-webdriver'
require 'json'
describe '6withitProfileUpdateResults' do
  before(:each) do
    @driver = Selenium::WebDriver.for :chrome
    @vars = {}
  end
  after(:each) do
    @driver.quit
  end
  it '6withitProfileUpdateResults' do
    @driver.get('http://localhost:3000/')
    @driver.manage.window.resize_to(1920, 1040)
    @driver.find_element(:link_text, 'Войти в аккаунт').click
    sleep 2
    @driver.find_element(:id, 'email').click
    sleep 2
    @driver.find_element(:id, 'email').send_keys('testuser@email.ru')
    @driver.find_element(:id, 'password').click
    @driver.find_element(:id, 'password').send_keys('123456')
    @driver.find_element(:name, 'commit').click
    sleep 2
    @driver.find_element(:link_text, 'Мой профиль').click
    sleep 2
    expect(@driver.find_element(:css, '.ms-5').text).to eq('testuser')
    @driver.find_element(:css, '.btn-success').click
    sleep 2
    @driver.find_element(:id, 'bench_press_max').click
    @driver.find_element(:id, 'bench_press_max').send_keys('10')
    @driver.find_element(:name, 'commit').click
    sleep 2
    expect(@driver.find_element(:css, 'tr:nth-child(1) > td:nth-child(2)').text).to eq('10.0 кг')
  end
end
