# Generated by Selenium IDE
require 'selenium-webdriver'
require 'json'

# Добавление в друзья пользователя и соревнования с ним
describe '7addFriendandcompetention' do
  before(:each) do
    @driver = Selenium::WebDriver.for :chrome
    @vars = {}
  end
  after(:each) do
    @driver.quit
  end
  it '7addFriendandcompetention' do
    @driver.get('http://localhost:3000/')
    @driver.manage.window.resize_to(1920, 1080)
    @driver.find_element(:link_text, 'Войти в аккаунт').click
    sleep 2
    @driver.find_element(:id, 'email').click
    @driver.find_element(:id, 'email').send_keys('testuser@email.ru')
    @driver.find_element(:id, 'password').click
    @driver.find_element(:id, 'password').send_keys('123456')
    @driver.find_element(:name, 'commit').click
    sleep 3
    @driver.find_element(:link_text, 'Пользователи').click
    sleep 2
    @driver.find_element(:link_text, 'd3metra').click
    sleep 2
    @driver.find_element(:css, '.btn-success').click
    sleep 2
    expect(@driver.find_element(:css, '.btn-warning').text).to eq('Отменить заявку')
    @driver.find_element(:link_text, 'Мой профиль').click
    sleep 2
    @driver.find_element(:id, 'dropdownMenuButton').click
    sleep 2
    @driver.find_element(:link_text, 'Выйти из аккаунта').click
    sleep 2
    @driver.find_element(:link_text, 'Войти в аккаунт').click
    sleep 2
    @driver.find_element(:id, 'email').click
    @driver.find_element(:id, 'email').send_keys('dt.71dt@mail.ru')
    @driver.find_element(:id, 'password').click
    @driver.find_element(:id, 'password').send_keys('Dimon2023')
    @driver.find_element(:name, 'commit').click
    sleep 2
    @driver.find_element(:link_text, 'Мой профиль').click
    sleep 2
    @driver.find_element(:id, 'friends-tab').click
    @driver.find_element(:css, '.btn-outline-success').click
    sleep 2
    @driver.find_element(:id, 'dropdownMenuButton').click
    sleep 2
    @driver.find_element(:link_text, 'Выйти из аккаунта').click
    sleep 2
    @driver.find_element(:link_text, 'Войти в аккаунт').click
    sleep 2
    @driver.find_element(:id, 'email').click
    @driver.find_element(:id, 'email').send_keys('testuser@email.ru')
    @driver.find_element(:id, 'password').click
    @driver.find_element(:id, 'password').send_keys('123456')
    @driver.find_element(:name, 'commit').click
    sleep 2
    @driver.find_element(:link_text, 'Мой профиль').click
    sleep 2
    @driver.find_element(:id, 'friends-tab').click
    sleep 2
    expect(@driver.find_element(:link_text, 'd3metra').text).to eq('d3metra')
    @driver.find_element(:link_text, 'Соревнования').click
    sleep 2
    @driver.find_element(:css, '.row:nth-child(1) > .btn').click
    sleep 2
    expect(@driver.find_element(:css, '#bench_press_max tr:nth-child(2) > .ps-5').text).to eq('10.0 кг')
  end
end
