# Generated by Selenium IDE
require 'selenium-webdriver'
require 'json'

# Изменение данных аккаунт и разлогин
describe '8updateUsersDataAndLogout' do
  before(:each) do
    @driver = Selenium::WebDriver.for :chrome
    @vars = {}
  end
  after(:each) do
    @driver.quit
  end
  it '8updateUsersDataAndLogout' do
    @driver.get('http://localhost:3000/')
    @driver.manage.window.resize_to(945, 1020)
    @driver.find_element(:link_text, 'Войти в аккаунт').click
    sleep 2
    @driver.find_element(:id, 'email').click
    @driver.find_element(:id, 'email').send_keys('testuser@email.ru')
    @driver.find_element(:id, 'password').click
    @driver.find_element(:id, 'password').send_keys('123456')
    @driver.find_element(:name, 'commit').click
    sleep 2
    @driver.find_element(:link_text, 'Мой профиль').click
    sleep 2
    @driver.find_element(:css, '#dropdownMenuButton > img').click
    @driver.find_element(:link_text, 'Редактировать данные').click
    sleep 2
    @driver.find_element(:id, 'user_password').click
    @driver.find_element(:id, 'user_password').send_keys('123456')
    @driver.find_element(:id, 'user_password_confirmation').click
    @driver.find_element(:id, 'user_password_confirmation').send_keys('123456')
    @driver.find_element(:id, 'user_old_password').click
    @driver.find_element(:id, 'user_old_password').send_keys('123456')
    @driver.find_element(:name, 'commit').click
    sleep 2
    expect(@driver.find_element(:css, '.notice-message').text).to eq('Данные успешно изменены')
    @driver.find_element(:id, 'dropdownMenuButton').click
    @driver.find_element(:link_text, 'Выйти из аккаунта').click
    sleep 2
    expect(@driver.find_element(:css, '.notice-message').text).to eq('Вы вышли из аккаунта')
  end
end
