# Generated by Selenium IDE
require 'selenium-webdriver'
require 'json'
describe '9deleteUser' do
  before(:each) do
    @driver = Selenium::WebDriver.for :chrome
    @vars = {}
  end
  after(:each) do
    @driver.quit
  end
  it '9deleteUser' do
    @driver.get('http://localhost:3000/')
    @driver.manage.window.resize_to(1920, 1080)
    @driver.find_element(:link_text, 'Войти в аккаунт').click
    sleep 2
    @driver.find_element(:id, 'email').click
    @driver.find_element(:id, 'email').send_keys('dt.71dt@mail.ru')
    @driver.find_element(:id, 'password').click
    @driver.find_element(:id, 'password').send_keys('Dimon2023')
    @driver.find_element(:name, 'commit').click
    sleep 2
    @driver.find_element(:link_text, 'Пользователи').click
    sleep 2
    @driver.find_element(:link_text, 'testuser').click
    sleep 2
    @driver.find_element(:css, '.btn-danger:nth-child(1)').click
    sleep 2
    expect(@driver.find_element(:css, '.btn-success').text).to eq('Добавить в друзья')
    @driver.find_element(:id, 'dropdownMenuButton').click
    @driver.find_element(:css, '.dropdown-item').click
    @driver.find_element(:css, 'body').click
    sleep 2
    expect(@driver.find_element(:css, '.notice-message').text).to eq('Аккаунт успешно удалён')
  end
end
